version: 2.1
jobs:
  build:
    working_directory: ~/circleci
    docker:
      - image: circleci/node:12.18.2
    steps:
        - checkout
        - run:
            name: update-npm
            command: 'sudo npm install -g npm@latest'
        - run:
            name: install-npm
            command: npm install
        - run:
              name: test
              command: jest test
